// do not edit this file
import fs from "fs";
import path from "path";
import BlogGrid from "./BlogGrid";
import BlogModal from "./BlogModal";

interface BlogPost {
  file: string;
  title: string;
}

export default function BlogPage() {
  const blogDir = path.join(process.cwd(), "public", "blog");
  const htmlFiles = fs.readdirSync(blogDir).filter((file) => file.endsWith(".html"));

  // Read <title> from HTML files
  const posts: BlogPost[] = htmlFiles.map((file) => {
    const content = fs.readFileSync(path.join(blogDir, file), "utf-8");
    const match = content.match(/<title>(.*?)<\/title>/i);
    return { file, title: match ? match[1] : file.replace(".html", "") };
  });

  return (
    <div
      style={{
        padding: "4rem 2rem",
        fontFamily: "system-ui, sans-serif",
        maxWidth: "1200px",
        margin: "0 auto",
      }}
    >
      <h1
        style={{
          fontSize: "2.5rem",
          fontWeight: "bold",
          marginBottom: "2rem",
          textAlign: "center",
        }}
      >
        Blog Posts
      </h1>

      {posts.length === 0 ? (
        <p style={{ textAlign: "center", color: "#555" }}>No blog posts found.</p>
      ) : (
        <BlogGrid posts={posts} />
      )}

      <BlogModal files={htmlFiles} />
    </div>
  );
}
